/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CodepenLink {
        /**
          * CSS code
         */
        "css"?: string;
        /**
          * semi-colon separate multiple files
         */
        "cssExternal"?: string;
        /**
          * CSS preprocessor
         */
        "cssPreProcessor"?: 'none' | 'less' | 'scss' | 'sass' | 'stylus';
        /**
          * CSS prefix
         */
        "cssPrefix"?: 'autoprefixer' | 'prefixfree' | 'neither';
        /**
          * CSS reset or normalisation
         */
        "cssStarter"?: 'normalize' | 'reset' | 'neither';
        /**
          * Description of new pen
         */
        "description"?: string;
        /**
          * Set which editors are open. In this example HTML open, CSS closed, JS open
         */
        "editors"?: string;
        /**
          * Code that should go inside <head></head>
         */
        "head"?: string;
        /**
          * HTML code
         */
        "html"?: string;
        /**
          * HTML classes
         */
        "htmlClasses"?: string;
        /**
          * HTML preprocessor
         */
        "htmlPreProcessor"?: 'none' | 'slim' | 'haml' | 'markdown';
        /**
          * When the Pen is saved, it will save as Private if logged in user has that privledge, otherwise it will save as public
         */
        "isPrivate"?: boolean;
        /**
          * JavaScript code
         */
        "js"?: string;
        /**
          * semi-colon separate multiple files
         */
        "jsExternal"?: string;
        /**
          * JavaScript preprocessor
         */
        "jsPreProcessor"?: 'none' | 'coffeescript' | 'babel' | 'livescript' | 'typescript';
        /**
          * Layout of the new pen
         */
        "layout"?: 'top' | 'left' | 'right';
        /**
          * If supplied, the Pen will save as a fork of this id. Note it's not the slug, but ID. You can find the ID of a Pen with `window.CP.pen.id` in the browser console.
         */
        "parent"?: string;
        /**
          * Title of new pen
         */
        "penTitle"?: string;
        /**
          * an array of strings
         */
        "tags"?: Array<string>;
    }
}
declare global {
    interface HTMLCodepenLinkElement extends Components.CodepenLink, HTMLStencilElement {
    }
    var HTMLCodepenLinkElement: {
        prototype: HTMLCodepenLinkElement;
        new (): HTMLCodepenLinkElement;
    };
    interface HTMLElementTagNameMap {
        "codepen-link": HTMLCodepenLinkElement;
    }
}
declare namespace LocalJSX {
    interface CodepenLink {
        /**
          * CSS code
         */
        "css"?: string;
        /**
          * semi-colon separate multiple files
         */
        "cssExternal"?: string;
        /**
          * CSS preprocessor
         */
        "cssPreProcessor"?: 'none' | 'less' | 'scss' | 'sass' | 'stylus';
        /**
          * CSS prefix
         */
        "cssPrefix"?: 'autoprefixer' | 'prefixfree' | 'neither';
        /**
          * CSS reset or normalisation
         */
        "cssStarter"?: 'normalize' | 'reset' | 'neither';
        /**
          * Description of new pen
         */
        "description"?: string;
        /**
          * Set which editors are open. In this example HTML open, CSS closed, JS open
         */
        "editors"?: string;
        /**
          * Code that should go inside <head></head>
         */
        "head"?: string;
        /**
          * HTML code
         */
        "html"?: string;
        /**
          * HTML classes
         */
        "htmlClasses"?: string;
        /**
          * HTML preprocessor
         */
        "htmlPreProcessor"?: 'none' | 'slim' | 'haml' | 'markdown';
        /**
          * When the Pen is saved, it will save as Private if logged in user has that privledge, otherwise it will save as public
         */
        "isPrivate"?: boolean;
        /**
          * JavaScript code
         */
        "js"?: string;
        /**
          * semi-colon separate multiple files
         */
        "jsExternal"?: string;
        /**
          * JavaScript preprocessor
         */
        "jsPreProcessor"?: 'none' | 'coffeescript' | 'babel' | 'livescript' | 'typescript';
        /**
          * Layout of the new pen
         */
        "layout"?: 'top' | 'left' | 'right';
        /**
          * If supplied, the Pen will save as a fork of this id. Note it's not the slug, but ID. You can find the ID of a Pen with `window.CP.pen.id` in the browser console.
         */
        "parent"?: string;
        /**
          * Title of new pen
         */
        "penTitle"?: string;
        /**
          * an array of strings
         */
        "tags"?: Array<string>;
    }
    interface IntrinsicElements {
        "codepen-link": CodepenLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "codepen-link": LocalJSX.CodepenLink & JSXBase.HTMLAttributes<HTMLCodepenLinkElement>;
        }
    }
}
